/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANDRES
 */
public class calculadora extends javax.swing.JFrame {

    double PrimerNumero;
    double SegundoNumero;
    double resultado; 
    String operador;
    
    
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JTextField();
        N1 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        N8 = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        Pantalla.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaActionPerformed(evt);
            }
        });
        getContentPane().add(Pantalla);
        Pantalla.setBounds(30, 50, 240, 60);

        N1.setBackground(new java.awt.Color(0, 0, 0));
        N1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N1.setForeground(new java.awt.Color(255, 255, 255));
        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1);
        N1.setBounds(20, 300, 60, 60);

        N2.setBackground(new java.awt.Color(0, 0, 0));
        N2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N2.setForeground(new java.awt.Color(255, 255, 255));
        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        getContentPane().add(N2);
        N2.setBounds(90, 300, 60, 60);

        N3.setBackground(new java.awt.Color(0, 0, 0));
        N3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N3.setForeground(new java.awt.Color(255, 255, 255));
        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3);
        N3.setBounds(160, 300, 60, 60);

        N4.setBackground(new java.awt.Color(0, 0, 0));
        N4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N4.setForeground(new java.awt.Color(255, 255, 255));
        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4);
        N4.setBounds(20, 230, 60, 60);

        N5.setBackground(new java.awt.Color(0, 0, 0));
        N5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N5.setForeground(new java.awt.Color(255, 255, 255));
        N5.setText("5");
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        getContentPane().add(N5);
        N5.setBounds(90, 230, 60, 60);

        N6.setBackground(new java.awt.Color(0, 0, 0));
        N6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N6.setForeground(new java.awt.Color(255, 255, 255));
        N6.setText("6");
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6);
        N6.setBounds(160, 230, 60, 60);

        N7.setBackground(new java.awt.Color(0, 0, 0));
        N7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N7.setForeground(new java.awt.Color(255, 255, 255));
        N7.setText("7");
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7);
        N7.setBounds(20, 160, 60, 60);

        N8.setBackground(new java.awt.Color(0, 0, 0));
        N8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N8.setForeground(new java.awt.Color(255, 255, 255));
        N8.setText("8");
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        getContentPane().add(N8);
        N8.setBounds(90, 160, 60, 60);

        N9.setBackground(new java.awt.Color(0, 0, 0));
        N9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N9.setForeground(new java.awt.Color(255, 255, 255));
        N9.setText("9");
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        getContentPane().add(N9);
        N9.setBounds(160, 160, 60, 60);

        N0.setBackground(new java.awt.Color(0, 0, 0));
        N0.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N0.setForeground(new java.awt.Color(255, 255, 255));
        N0.setText("0");
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        getContentPane().add(N0);
        N0.setBounds(20, 370, 60, 60);

        mas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mas.setText("+");
        mas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        getContentPane().add(mas);
        mas.setBounds(230, 360, 50, 70);

        menos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        menos.setText("-");
        menos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        getContentPane().add(menos);
        menos.setBounds(230, 310, 50, 40);

        dividir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dividir.setText("÷");
        dividir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        getContentPane().add(dividir);
        dividir.setBounds(230, 210, 50, 40);

        multiplicar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        multiplicar.setText("x");
        multiplicar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicar);
        multiplicar.setBounds(230, 260, 50, 40);

        punto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        punto.setText(".");
        punto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        getContentPane().add(punto);
        punto.setBounds(90, 370, 60, 60);

        igual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        igual.setText("=");
        igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual);
        igual.setBounds(160, 370, 60, 60);

        borrar.setBackground(new java.awt.Color(255, 0, 51));
        borrar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        borrar.setText("C");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar);
        borrar.setBounds(230, 160, 50, 40);

        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANDRES\\OneDrive\\Escritorio\\calculadoratr 2.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(310, 465));
        jLabel2.setMinimumSize(new java.awt.Dimension(310, 465));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 310, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
String Numero = Pantalla.getText() + N1.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N1ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
Pantalla.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
String Numero = Pantalla.getText() + N7.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N7ActionPerformed

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
String Numero = Pantalla.getText() + N2.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
String Numero = Pantalla.getText() + N3.getText();
        Pantalla.setText(Numero);
        // TODO add your handling code here:
    }//GEN-LAST:event_N3ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        String Numero = Pantalla.getText() + N0.getText();
        Pantalla.setText(Numero);
    }//GEN-LAST:event_N0ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
String Numero = Pantalla.getText() + N4.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
String Numero = Pantalla.getText() + N5.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
String Numero = Pantalla.getText() + N6.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N6ActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
String Numero = Pantalla.getText() + N8.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N8ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
String Numero = Pantalla.getText() + N9.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_N9ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
String Numero = Pantalla.getText() + punto.getText();
        Pantalla.setText(Numero);        // TODO add your handling code here:
    }//GEN-LAST:event_puntoActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    operador = "+";
    }//GEN-LAST:event_masActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    operador = "-";        // TODO add your handling code here:
    }//GEN-LAST:event_menosActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    operador = "x";        // TODO add your handling code here:
    }//GEN-LAST:event_multiplicarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
    PrimerNumero = Double.parseDouble(Pantalla.getText());
    Pantalla.setText(" ");
    operador = "÷";        // TODO add your handling code here:
    }//GEN-LAST:event_dividirActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
       SegundoNumero = Double.parseDouble(Pantalla.getText());
       
        switch (operador) {
            case "+":
                resultado = PrimerNumero + SegundoNumero;
                Pantalla.setText(Double.toString(resultado));
                break;
            case "-":
                resultado = PrimerNumero - SegundoNumero;
                Pantalla.setText(Double.toString(resultado));
                break;
            case "x":
                resultado = PrimerNumero * SegundoNumero;
                Pantalla.setText(Double.toString(resultado));
                break;
            case "÷":
                resultado = PrimerNumero / SegundoNumero;
                Pantalla.setText(Double.toString(resultado));
                break;
            default:
                break;
        }
        if (resultado == (int) resultado) {
        Pantalla.setText(String.valueOf((int) resultado));
    } else {
        Pantalla.setText(String.valueOf(resultado));
    }
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton borrar;
    private javax.swing.JButton dividir;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton punto;
    // End of variables declaration//GEN-END:variables
}
